// Generated by npm run recognition:generate.
// Edit content/reader-recognition.csv instead of this file.

export interface ReaderComment {
  id: number;
  name: string;
  comment: string;
  featured?: boolean;
  featureTitle?: string;
  featureExcerpt?: string;
  date?: string;
  source?: string;
  sourceTitle?: string;
  sourceUrl?: string;
}

export const READER_COMMENTS: ReaderComment[] = [
  {
    id: 1,
    name: "Gilli B.",
    comment: "Beautifully put... that landed. Thank you",
    source: "Facebook",
    sourceTitle: "The Things That Find Us",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3073059316223770/"
  },
  {
    id: 2,
    name: "Kathleen M.",
    comment: "Write On.",
    source: "Facebook",
    sourceTitle: "The Things That Find Us",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3073059316223770/"
  },
  {
    id: 3,
    name: "Lianne C.",
    comment: "Wow Jonathan. Just wow.",
    source: "Facebook",
    sourceTitle: "The Things That Find Us",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3073059316223770/"
  },
  {
    id: 4,
    name: "Madz T.",
    comment: "What stunning threads of convergence",
    source: "Facebook",
    sourceTitle: "The Things That Find Us",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3073059316223770/"
  },
  {
    id: 5,
    name: "Rose J.",
    comment: "Love this Jonathan, gentle gentle space I'm grateful for",
    source: "Facebook",
    sourceTitle: "The Sovereign Witness of the Rupture",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3072254542970914/"
  },
  {
    id: 6,
    name: "Rowan D.",
    comment: "Yes! Thank you! We need to do this work!",
    source: "Facebook",
    sourceTitle: "The Sovereign Witness of the Rupture",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3072254542970914/"
  },
  {
    id: 7,
    name: "Leonie J.",
    comment: "I'm watching this space with great anticipation! To scroll and see a post by yourself gets my heart and brain pumping. Knowing we are about to read something that will resonate in my bones and touch my soul: 'To live inside a clean house built by other hands, using words we did not write', wow! Deep but so true! And then spend our whole lives asking questions we shouldn't have to, carrying the weight of a decision we never got to make.",
    source: "Facebook",
    sourceTitle: "The Sovereign Witness of the Rupture",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3072254542970914/"
  },
  {
    id: 8,
    name: "Faith L.",
    comment: "Well done. I like that: 'The state owns the record. But the body holds the testimony.' I might add that, since my mother was incarcerated when I was born, the state also claimed ownership over her body and movement. They transferred her from prison to a hospital to give birth so the prison address would not appear on the original birth certificate. Even the record itself was managed, edited, and sanitized. But the body remembers what the archive tries to conceal. #PunishedInUtero",
    source: "Facebook",
    sourceTitle: "The Sovereign Witness of the Rupture",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3072254542970914/"
  },
  {
    id: 9,
    name: "Michele C.",
    comment: "I love this x",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 10,
    name: "Rachel T.",
    comment: "It's wild how you put into words so much of what I experience. I've never really considered that my breathing could be linked to being separated at birth and placed somewhere completely foreign. When you think about it, any animal baby taken from its mother is going to be impacted; the body really does keep the score (brilliant book, by the way). The body reacts before the mind catches up. The restricted breathing is a beast: I remember going to the doctor convinced I had asthma... ❤️ Once again, you've captured a lived experience that feels so familiar, yet has never quite been expressed like this. Beautifully done.",
    featured: true,
    featureTitle: "The Body Knew First",
    featureExcerpt: "You've captured a lived experience that feels so familiar, yet has never quite been expressed like this.",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 11,
    name: "AJ A.",
    comment: "Beautiful!",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 12,
    name: "Barbara W.",
    comment: "Yes",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 13,
    name: "Jo P.",
    comment: "Wow, yet again you describe how I feel completely accurately ❤️",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 14,
    name: "Deborah Ann J.",
    comment: "This is all so true and so beautifully elucidated. I have saved this to reread as it so well describes my experience from the IBS to the feeling of crushing pressure as if drowning in water many fathoms deep. I also watched others live a freedom of natural place in the world that I never knew.",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 15,
    name: "Fran E.",
    comment: "Wow. I used to tell my mom I felt sick and she told me I was making it up to get attention or stay home from school. I wasn't. Fifty years later with my boyfriend asking me... why do you always sigh like that? I didn't realize I did that, but I do. Now I know why. I viscerally recognize your words. Thank you.",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 16,
    name: "Joanne Z.",
    comment: "Thank you for this beautifully written piece. I felt myself nodding and breathing deeply as I read it. I will reread it many times; so many lines feel like my feelings spread out on the screen. Just beautiful!",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 17,
    name: "Kelley P.",
    comment: "This made me cry with its truth. I recognize myself in every word. Thank you so much for sharing this.",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 18,
    name: "Jane H.",
    comment: "Wow! This stopped in my tracks as I was scrolling...",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 19,
    name: "Debra J. R.",
    comment: "How absolutely poignant. How completely encompassing. Thank you.",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 20,
    name: "Linda P.",
    comment: "I can relate and can't take a deep breath ever. I used to wonder if my family doctor noticed, especially as a young child.",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 21,
    name: "Julie C.",
    comment: "Don't stop writing! Your words are beautiful and so spot on. I have been very interested in epigenetics and the memories of trauma that become embedded in our bodies. I've had gut, spine, neck issues and heart, all of which I'm convinced are outward expressions of trauma. A lifetime trying to replace this with love... of self, inner being, and gratitude (not as a victim but for our magnificent earth and her expression of love). Thank you",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 22,
    name: "CopperAsparagus17",
    comment: "Thank you for sharing this. It echoes exactly how I feel and so much that I've been trying to make sense of for so many years. Breath work has helped me as has chiropractic work on my diaphragm. Feeling very emotional after reading this.",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 23,
    name: "Shari Swender T.",
    comment: "Somebody please like this so I can come back and finish. Don't have time to read the whole thing right now",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 24,
    name: "Rose L.",
    comment: "That resonates with me too. Beautifully written, thoughtful and, for me, meaningful. Thank you. Your thoughts and words mean a lot.",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 25,
    name: "Tom V.",
    comment: "That was a beautiful piece, and it resonated with me so well.",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 26,
    name: "Hope W.",
    comment: "I can't breathe deeply. When I try, my body stops. It becomes so uncomfortable I just can't continue. I thought I just wasn't disciplined enough",
    source: "Facebook",
    sourceTitle: "The Breath We Never Took",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3069421173254251/"
  },
  {
    id: 27,
    name: "Andrea L.",
    comment: "Absolutely. I live like a meerkat on top of a mound. A surveilance kat. Even when im asleep 🥺",
    source: "Facebook",
    sourceTitle: "The Standing Watch",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3087440034785698/"
  },
  {
    id: 28,
    name: "Rosemary P.",
    comment: "Jonathan, I inevitably identify with your words. But today reading this you’ve put into words feelings that I have never been able to articulate fully. I will read and re read this many times. To say I’m grateful for your writing doesn’t convey the thankfulness I feel. Thankyou Thankyou Thankyou x",
    featured: true,
    featureTitle: "Words for What I Couldn't Say",
    featureExcerpt: "You've put into words feelings that I have never been able to articulate fully.",
    source: "Facebook",
    sourceTitle: "The Standing Watch",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3087440034785698/"
  },
  {
    id: 29,
    name: "Carla H.",
    comment: "Yes! This right here - beautiful! \"you have, more than once, taken it off just to end the waiting.\" Oh how I understand this one!",
    source: "Facebook",
    sourceTitle: "The Standing Watch",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3087440034785698/"
  },
  {
    id: 30,
    name: "Gilli B.",
    comment: "Magical",
    source: "Facebook",
    sourceTitle: "The Standing Watch",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3087440034785698/"
  },
  {
    id: 31,
    name: "Julie C.",
    comment: "Again ... \"wordsmith-ing\" at its best. Thank you. I've tended to run towards any possible threat or potential threat to meet it head on and to deal with it (or be dealt with). The waiting and gut churning fear is terrifying for me. I've learned, in my later years, to stop, look, step aside, breathe and accept. It's taken 60 years.",
    source: "Facebook",
    sourceTitle: "The Catalogue of Nearlys",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3084210198442015/"
  },
  {
    id: 32,
    name: "Vanessa C.",
    comment: "Thank You sooo much",
    source: "Facebook",
    sourceTitle: "The Catalogue of Nearlys",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3084210198442015/"
  },
  {
    id: 33,
    name: "Leonie J.",
    comment: "Wow! Every time I read one of your posts it feels like you have crawled into my psyche and dissected it and then splattered your findings, the inner workings of me, into a post I didn’t have the courage to write. Your musings touch me at soul level, the only way I can describe your words. I also normally read them in the wee hours of the morning (it’s currently 4.30am) and I’m not sure if that hits me more because my brain has yet to put on one of its many masks it wears throughout the day. Whatever..keep those thoughts coming because they are feeding a part of me I didn’t know was starving",
    featured: true,
    featureTitle: "The Starving Part",
    featureExcerpt: "Your words are feeding a part of me I didn't know was starving.",
    source: "Facebook",
    sourceTitle: "The Catalogue of Nearlys",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3084210198442015/"
  },
  {
    id: 34,
    name: "David C.",
    comment: "Thank you for eloquently describing what we often feel but have no words. This piece resonants with me in so many ways",
    source: "Facebook",
    sourceTitle: "The Catalogue of Nearlys",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3084210198442015/"
  },
  {
    id: 35,
    name: "Elizabeth B.",
    comment: "Bravery not sabotage. I see all ours clearly now. It took me 27 years to limp away from the narcissist I married AND the last four years to fully embrace how my dysfunctional adoptive survival has been playing out in my programmed life patterns. Personal bravery. I’ll never forget the moment my face slap of bravery hit me…sitting around a table with his family thirty seconds into sharing some of my adoption journey when he says, \"hurry up, no one wants to hear a long story from you.\" I would truly love to know if any of you have long term brave people in your lives? I’ve had momentary moments…",
    source: "Facebook",
    sourceTitle: "The Catalogue of Nearlys",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3084210198442015/"
  },
  {
    id: 36,
    name: "Leslie M.",
    comment: "Ohhhh yes you know exactly how to explain these complicated experiences and emotions. Thank you, Jonathan Lyon",
    source: "Facebook",
    sourceTitle: "The Catalogue of Nearlys",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3084210198442015/"
  },
  {
    id: 37,
    name: "Puppyraiser3",
    comment: "Your writing is absolutely incredible. The way you put your thoughts to paper is mesmerizing. Even more incredible, is knowing there’s someone out there that feels almost exactly the way I do. It’s like you know me so well, while never having met, or had so much as a conversation. It’s nice to not be so alone, but heartbreaking that anyone else felt, or feels, the way I do. I feel like I could’ve written this myself….but, I could never put it into words the way you do. It’s incredible. I’m grateful for you, Jonathon.",
    source: "Facebook",
    sourceTitle: "The Catalogue of Nearlys",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3084210198442015/"
  },
  {
    id: 38,
    name: "Bonnie B.",
    comment: "You give words to the unexplainable parts of me. This is beautiful. Thank you.",
    source: "Facebook",
    sourceTitle: "The Catalogue of Nearlys",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3084210198442015/"
  },
  {
    id: 39,
    name: "Elizabeth Trezise B.",
    comment: "Your writing is breathtaking and I find myself nodding incessantly while reading. You capture our experience so beautifully. So when are you writing that book??",
    source: "Facebook",
    sourceTitle: "The Catalogue of Nearlys",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3084210198442015/"
  },
  {
    id: 40,
    name: "Lorri R.",
    comment: "Thank you for this.",
    source: "Facebook",
    sourceTitle: "The Catalogue of Nearlys",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3084210198442015/"
  },
  {
    id: 41,
    name: "Lorri R.",
    comment: "The marketplace for ME is my adult children. It’s too uncomfortable to see my broken parts and try to touch them.",
    source: "Facebook",
    sourceTitle: "Being Seen and Unseen",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3080662815463420/"
  },
  {
    id: 42,
    name: "Marguerite B.",
    comment: "I really couldn’t tap a reaction to this. I don’t like or love it. I don’t need to tap care because i know it is ultimately futile. I won’t tap shock because I’m past it; laughing is inappropriate, crying is not strong enough and I’m tired of anger. This is an existential issue. I see you have chosen to wrestle with this issue using words. There are no words (certainly not beautiful words) in this process we undergo some call life (others call hel). May all beings find peace.",
    source: "Facebook",
    sourceTitle: "Being Seen and Unseen",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3080662815463420/"
  },
  {
    id: 43,
    name: "Janet R.",
    comment: "Thank you for putting into words what I can only feel. Being in the presence of others with the same wound is the only place I found understanding. Even then I was told by a fellow adoptee that I seemed fine......so we'll do we learn to hide. I was able to give her an example of when I felt the pain earlier that day and reassured her it happens multiple times daily......you can never be unadopted.",
    featured: true,
    featureTitle: "The Wound We Learn to Hide",
    featureExcerpt: "Thank you for putting into words what I can only feel.",
    source: "Facebook",
    sourceTitle: "Being Seen and Unseen",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3080662815463420/"
  },
  {
    id: 44,
    name: "Rose J.",
    comment: "I see you...I talk to the wind & the wind calls my name...tena koe e hoa",
    source: "Facebook",
    sourceTitle: "Being Seen and Unseen",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3080662815463420/"
  },
  {
    id: 45,
    name: "Gilli B.",
    comment: "We can. I can. Tribe members when we are called to gather in unspoken connection. I see you as you see me. With big love",
    source: "Facebook",
    sourceTitle: "Being Seen and Unseen",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3080662815463420/"
  },
  {
    id: 46,
    name: "Linda D.",
    comment: "This is a great examination of the adoptee experience. I describe it as the disparity between the shared narrative of adoption and my lived experience. It set me on a path of sensitization to bullshit and always swimming against the mainstream.",
    date: "2026-06-09",
    source: "Facebook",
    sourceTitle: "Deconstructed Smoke",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3089399391256429/"
  },
  {
    id: 47,
    name: "Rosemary P.",
    comment: "Again your words resonate . I read a file from OT in NZ when I received it the other week. And at age 30 upon discovery that my twin sister and I were adopted , I was reassuring everyone , social workers , A parents, Birth Father that we had such a happy childhood. We didn’t really, we had a complicated childhood with an unstable AM where looking back, being loved meant being the good adoptee. I got good at reading the room, watching to see how people react, reading their minds .\nTrying to undo all that now with Somatic work, it’s hard and some days doesn’t seem worth it . But on we go .",
    date: "2026-06-09",
    source: "Facebook",
    sourceTitle: "Deconstructed Smoke",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3089399391256429/"
  },
  {
    id: 48,
    name: "Leonie J.",
    comment: "“All the world’s a stage,\nAnd all the men and women merely players;\nThey have their exits and their entrances;\nAnd one man in his time plays many parts” … ahhh William a man before his time! Once again you have crawled into my brain and put my life into words for all to read. Although I use the analogy of ‘masks’ instead of coats. I own and wear many, many masks.\n and have done all my life depending on the situation I find myself in to which one I wear. I used to believe it was part of my ASD/ADHD but only recently have realised that it’s my life’s best survival instincts. It’s all in the knowledge of which mask to wear in which situation and if there is, or ever was a real face under all those masks.\nOnce again I bow down to your words and letters that you have placed on the page.",
    date: "2026-06-09",
    source: "Facebook",
    sourceTitle: "Deconstructed Smoke",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3089399391256429/"
  },
  {
    id: 49,
    name: "Rachel T.",
    comment: "Damn, you’re good alright!! Wow! That’s exactly how I have felt my whole life, like an actor and in my home with four birth siblings to my parents (who I love deeply)... an imposter! But you’re right, I knew I was acting, always the fool, the pleaser, the cleaner, the clown, the room softener (that’s a good one) and nobody knew it was part of the debt repayment of being an adoptee. Always bringing the high energy to whanau gatherings to lift the mood and the room, a drink in the hand, seeking attention and reactions so people knew I existed. Thanks again, another gold nugget! Seeing and reading my experiences in words feels….makes me feel heard like I’m not alone. Thank you",
    featured: true,
    featureTitle: "Heard, and Not Alone",
    featureExcerpt: "Seeing and reading my experiences in words makes me feel heard, like I'm not alone.",
    date: "2026-06-09",
    source: "Facebook",
    sourceTitle: "Deconstructed Smoke",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3089399391256429/"
  },
  {
    id: 50,
    name: "Catherine L.",
    comment: "A perfect capture of one angle of the dissociated Adoptee childhood. In one sense, isn’t the adopted child the only real thing in the room when the room is full of fake adults?",
    date: "2026-06-09",
    source: "Facebook",
    sourceTitle: "Deconstructed Smoke",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3089399391256429/"
  },
  {
    id: 51,
    name: "Marguerite B.",
    comment: "This is why I don’t write lol!",
    date: "2026-06-09",
    source: "Facebook",
    sourceTitle: "Deconstructed Smoke",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3089399391256429/"
  },
  {
    id: 52,
    name: "Jean S.",
    comment: "It's difficult to watch the pained expressions from those for whom you performed to realize that I was no longer in on the performance. I always took it as a right to both not be seen (transracial adoption) and the right to be who I am and not what people told me I was.",
    date: "2026-06-09",
    source: "Facebook",
    sourceTitle: "Deconstructed Smoke",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3089399391256429/"
  },
  {
    id: 53,
    name: "Kathleen M.",
    comment: "Oui Chef!\nA very raw experience.",
    date: "2026-06-09",
    source: "Facebook",
    sourceTitle: "Deconstructed Smoke",
    sourceUrl: "https://www.facebook.com/groups/onhumanadoption/posts/3089399391256429/"
  },
  {
    id: 54,
    name: "Chare",
    comment: "Adoption to a baby IS abduction. We have to start framing this adoption experience from our perspective.",
    date: "2026-05-21",
    source: "Substack",
    sourceTitle: "By Another Name",
    sourceUrl: "https://jonathanlyon.substack.com/p/by-another-name"
  }
];
